[package]
name = "vm_buffers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vm_memory = { git = "https://github.com/tech-paws/vm_memory.git" }
